name: Scale Fly App Based on Carbon Intensity

on:
  push:
    branches:
      - main

jobs:
  scale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run scaling script
        run: node scale.mjs
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
