name: Scale Fly App Based on Carbon Intensity

on:
  push:
    branches:
      - main

jobs:
  scale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run scaling script
        run: |
          export CARBON_API_TOKEN_ID=${{ secrets.CARBON_API_TOKEN_ID }}
          export CARBON_API_TOKEN_SECRET=${{ secrets.CARBON_API_TOKEN_SECRET }}
          node scale.mjs
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}